### ISSUE TITLE
Allow arbitrary Aff actions?

### ISSUE THREAD

**Issue by Thimoteus** [juspay/purescript-presto#11]
With the current state, if I want to run an Aff action that's parametrized by an effect that doesn't show up in the definition of [AppEffects](https://github.com/juspay/purescript-presto/blob/master/src/Presto/Core/Types/App.purs#L21) I need to do some `unsafeCoerceAff`ing: this is because [doAff](https://github.com/juspay/purescript-presto/blob/master/src/Presto/Core/Types/Language/Flow.purs#L137) uses a rank 2 type, so you can *only* pass it an argument that has the type `forall eff. AppFlow eff s`; in particular the choice of effects are controlled by presto, not by the user.

I can see a few ways of resolving this:

1. Maintain the current state, which requires users to `unsafeCoerceAff`
2. Pull the effect row out into the definition of `Flow`
3. Instead of `Aff`, use [`IO`](https://github.com/slamdata/purescript-io)

**Comment by sachin009** [comment]
Closing for now. Please open a new issue in case required.
