### ISSUE TITLE
webpack Failed to compile example 'billpay-presto-ui' 

### ISSUE THREAD

**Issue by alainpatrick** [juspay/purescript-presto#12]
Hi,
I tried to follow this example which is in the Presto-Guide but i'm getting some errors.

`ERROR in ./node_modules/presto-ui/lib/index.js
Module not found: Error: Can't resolve './presto.development.js' in '/purescript-presto/examples/billpay-presto-ui/node_modules/presto-ui/lib'
 @ ./node_modules/presto-ui/lib/index.js 6:19-53
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js`

`ERROR in ./node_modules/presto-ui/lib/index.js
Module not found: Error: Can't resolve './presto.production.min.js' in '/purescript-presto/examples/billpay-presto-ui/node_modules/presto-ui/lib'
 @ ./node_modules/presto-ui/lib/index.js 4:19-56
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js`

Any idea why this is happening?

**Comment by georgevarghese185** [comment]
Try updating the `presto-ui` dependency to `^0.3.4` inside the billpay example. That should do it.

**Comment by dilipzotha** [comment]
Hi Alain,

I have updated the version of presto-ui library. Can you pull the latest changes, it should work now.

**Comment by alainpatrick** [comment]
Thank you so much!
Works without errors now.
