### ISSUE TITLE
Comparison with Concur UI lib for Haskell?

### ISSUE THREAD

**Issue by ajnsit** [juspay/purescript-presto#4]
We seem to have struck upon the same idea at the same time!

I just saw the talk here - https://www.youtube.com/watch?v=HLEwYghBjo8 and your framework strongly resembles a Haskell UI lib I've been writing called Concur, available here - https://github.com/ajnsit/concur. I have even been meaning to write a Purescript version (https://github.com/ajnsit/concur-purescript).

There seems to be lots of opportunity for collaboration. What do you think?

**Comment by dilipzotha** [comment]
Interesting, we have been actively evolving the Presto Ecosystem and roadmap. 
I was going through concur and totally agree with you on your thoughts on FRP. We are also planning to add FRP based widgets to accommodate for streaming data to UI. Will be happy to hear your thoughts and discuss. Please write to us at presto@juspay.in.
